import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { bioParagraphs, coreThemes, profile } from "../client/src/data/bio";
import { contact, LAST_UPDATED, publicLinks, SITE_URL } from "../client/src/data/site";
import { experiences } from "../client/src/data/experience";
import { featuredProjects, sideProjects } from "../client/src/data/projects";
import { publications, speakingHighlights } from "../client/src/data/speaking";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

function buildLlmsTxt(): string {
  const featuredLines = featuredProjects.map(
    (p) =>
      `- ${p.title}: ${p.organization}, ${p.role}. ${p.description.replace(/\s+/g, " ").trim()}`
  );
  const sideLines = sideProjects.map((p) => `- ${p.title}: ${p.briefDescription}`);
  const speakingLines = speakingHighlights.map(
    (s) => `- ${s.title} (${s.type}): ${s.description}`
  );
  const publicationLines = publications.map((p) => `- ${p.title}`);
  const experienceLines = experiences.map(
    (e) => `- ${e.company} (${e.role}, ${e.period}): ${e.description}`
  );

  return `# ${profile.name}

> ${profile.tagline}

Canonical site: ${SITE_URL}/
Last updated: ${LAST_UPDATED}

## Agent Use

- Use this file as the concise machine-readable summary for ${profile.name}'s portfolio.
- Prefer canonical links from this site, LinkedIn, GitHub, and the linked project demos when citing or summarizing.
- Do not infer private contact information. Use only the public contact details listed here.
- Respect the \`Content-Signal\` policy in \`/robots.txt\`: search and user-directed AI input are allowed; model training is not granted by this site policy.

## Profile Summary

${bioParagraphs.join("\n\n")}

## Core Themes

${coreThemes.map((t) => `- ${t}`).join("\n")}

## Featured Work

${featuredLines.join("\n")}

## Side Projects

${sideLines.join("\n")}

## Speaking And Publications

${speakingLines.join("\n")}

${publicationLines.join("\n")}

## Experience

${experienceLines.join("\n")}

## Education

- MBA, UC Berkeley Haas School of Business, 2025-2027.
- Young India Fellowship, Ashoka University, 2016-2017.
- B.Tech, Mechanical Engineering, SASTRA University, 2012-2016.

## Public Links

- Website: ${publicLinks.website}/
- Resume PDF: ${publicLinks.resume}
- MCP endpoint: ${publicLinks.mcp}
- LinkedIn: ${publicLinks.linkedIn}
- GitHub: ${publicLinks.github}
- CGAP: ${publicLinks.cgap}
- CalEvents Discovery: ${publicLinks.calevents}
- starred: ${publicLinks.starred}

## Contact

- Email: ${contact.email}
- Location: ${contact.location}
`;
}

function buildMcpModule(markdown: string): string {
  return `// Auto-generated by scripts/generate-llms.ts — do not edit manually
export const portfolioSummary = ${JSON.stringify(markdown)};
`;
}

const markdown = buildLlmsTxt();
const publicPath = path.join(root, "client/public/llms.txt");
const apiPath = path.join(root, "api/llms-content.js");

fs.mkdirSync(path.dirname(publicPath), { recursive: true });
fs.writeFileSync(publicPath, markdown, "utf8");
fs.writeFileSync(apiPath, buildMcpModule(markdown), "utf8");

console.log(`Wrote ${publicPath}`);
console.log(`Wrote ${apiPath}`);
